### ISSUE TITLE
Conflict with table sorting

### ISSUE THREAD

**Issue by bjarnef** [warrenbuckley/Analytics#10] opened 2014-10-01 21:09 UTC
When there are multiple tables in a view, the table sorting is in conflict with each other and in some cases change sorting in another table. The table sorting needs to be restricted to sort only the table itself.

**Comment by warrenbuckley** [comment] 2015-02-17 16:09
@bjarnef any updates on this or is this no longer a problem?

**Comment by bjarnef** [comment] 2015-02-17 16:17
I think it is still a problem, but only when there are multiple tables on a page. I think the scope should be isolated or something like that.
I haven't seen any examples with multiple tables with sorting on a page as a basis examples. Then it has been a completely Angular table module and I didn't thought that is neccessary to use..

**Comment by warrenbuckley** [comment] 2015-02-17 16:21
I thought it was working but maybe I imagined it. As I haven't been using this much & project got bit neglected. Trying to change that. So do most reports have multiple tables so I can look & test this out?

**Comment by bjarnef** [comment] 2015-02-17 16:31
Some views only contains 1 table, but I think half of the views has 2 or 3 tables.
if it isn't easy to find a fix, maybe there is a useful table directive to handle the sorting.. The tablesorter I mentioned seems to work even when there are multiple tables on a page.

**Comment by bjarnef** [comment] 2015-02-24 08:19
@warrenbuckley maybe this is an option for table sorting? http://zizzamia.com/ng-tasty/directive/table

**Comment by warrenbuckley** [comment] 2015-02-24 09:23
Thanks @bjarnef I am going to try and look at sorting today to resolve this. Did you do the original table sorting? As I can't find the JS function sort called from ng-click on the headers?

**Comment by bjarnef** [comment] 2015-02-24 09:33
@warrenbuckley , yes the columns that should have sorting trigger the sort function on ng-click. In the view it looks like this https://github.com/warrenbuckley/Analytics/blob/master/Analytics/App_Plugins/Analytics/backOffice/AnalyticsTree/partials/keywords.html#L17 and then the controller have this part https://github.com/warrenbuckley/Analytics/blob/master/Analytics/App_Plugins/Analytics/backOffice/AnalyticsTree/controllers/Keyword.Controller.js#L9-L27 and this to sort and display the sort icon just after the data is loaded https://github.com/warrenbuckley/Analytics/blob/master/Analytics/App_Plugins/Analytics/backOffice/AnalyticsTree/controllers/Keyword.Controller.js#L59-L64

**Comment by warrenbuckley** [comment] 2015-02-24 09:41
OK thanks @bjarnef I must have been blind yesterday!
The sort function could probably be tweaked to take in a scope or reference to the table to sort, as this will obviously apply to all tables on the page which is what it is doing.

Or alternatively wrap this up into a directive perhaps. Just concerned we are adding more libraries and potentially more page weight if we don't need all the features of these more complex table sorting plugins?

Thoughts?

**Comment by bjarnef** [comment] 2015-02-24 10:10
yes, I like to keep it simple, but also think the features to sort the column and check with the type .. e.g. so number not is sorted like 1, 10, 2, 23, 2, ... but 1, 2, 10, 23

is think this one is quite small https://github.com/mattiash/angular-tablesort/blob/master/js/angular-tablesort.js (~ 8KB) .. maybe just "borrow" the code and wrap it in our own directive?

**Comment by warrenbuckley** [comment] 2015-02-24 10:12
Ah as it's only 8KB then probably easier just to use the library in that case @bjarnef ?

**Comment by bjarnef** [comment] 2015-02-24 10:16
yes, if you have time for it, you can maybe do a test and see how it works?

**Comment by abjerner** [comment] 2015-02-24 10:26
There is a lot of comments to read through, so I'm not sure whether you have discussed this. Some tables (eg. "Views") will require server side sorting.

An example could be that the page with the most pageviews is not shown in the results since the table is initially sorted by most views.

**Comment by warrenbuckley** [comment] 2015-02-24 10:29
@abjerner I have not thought about that problem/issue. So every time we do a sort we will need to do another API call and refetch the data or is it possible to grab the entire dataset in JSON so we can then sort entirely client side then?

**Comment by abjerner** [comment] 2015-02-24 10:46
I think it depends from view to view. Eg *Views*, *Language* and *Country* may require server side sorting, while others like *Social Network* and *Devices* can be sorted via JS.

As far as I remember, the Analytics Data API has a limit of 1000 items per page, so it could be sufficient to just pull the first 1000 results. Theoretically it may still be an issue, but the risk of encountering the issue is a lot smaller.

**Comment by abjerner** [comment] 2015-02-24 10:50
And by server side sorting I mean letting the Analytics API sort the results for us.

**Comment by warrenbuckley** [comment] 2015-02-24 10:52
@abjerner I would say lets just fetch a 1000 results for now and implement paginated/sorted tables.
The initial request for the data the API can sort for us but once we have the JSON payload in the browser/client then let JS do it's job and sort clientside IMO

**Comment by bjarnef** [comment] 2015-02-24 10:57
I don't understand why you need server side sorting, when the data is fetched from Analytics via the API, you can just use Angular to sort the result set. Unless you need more data (like when you change the date range), I don't see a need to make a new call to the server - but you can of course always return the data from the API in a default sort order.

**Comment by warrenbuckley** [comment] 2015-02-24 10:58
@bjarnef the results from the API comes back as a max of 1000 items so if you have a massive site and need more data than the first 1000 items about pages & their page views then it would need to be paginated and another request sent back to the API

**Comment by bjarnef** [comment] 2015-02-24 11:00
anyway the ng-repeat will be slow if you have 10K rows, where something like infinite scroll or paging is a way to solve it. Is there set a limit in the API how many results to return?

**Comment by warrenbuckley** [comment] 2015-02-24 11:06
@bjarnef agreed but it's not 10k but 1K but will still make client side slow & unresponsive. @abjerner whats the default page size from Google's Analytics API?

My sites that I have under my own personal account are small so I will not be able to test paged requests. Do we think this is a non issue for now and perhaps deal with it later if someone has large data sets??

**Comment by bjarnef** [comment] 2015-02-24 11:06
ahh okay.. had I bachelor thesis few months ago, where I returned 18K orders from uCommerce to see how AngularJS handle that.. but quickly learned that it needs to be broken into smaller chunks.

**Comment by bjarnef** [comment] 2015-02-24 11:10
@warrenbuckley but even it initially sorted by most views, pageviews usually is close related to visits/views - more pageviews usually also means more visits. So I think most pageviews will probably be in the top result too.

**Comment by warrenbuckley** [comment] 2015-02-24 11:19
OK seems like we may not need to deal with this for now and raise as a new issue on GitHub tracker if this becomes a problem with people with larger datasets.

**Comment by abjerner** [comment] 2015-02-24 11:22
This will probably only be an issue in "edge" cases, so it shouldn't be a problem saving it for later. I just wanted to point out that it *may* be an issue.

@warrenbuckley I think the default limit is 25.

**Comment by warrenbuckley** [comment] 2015-02-24 21:44
OK guys @bjarnef & @abjerner I am stumped this evening trying to implement angular-tablesort
https://github.com/mattiash/angular-tablesort

As it's a module I am unsure to inject this module to use it in this controller such as BrowserController.js any thoughts or am I being just plain dumb??

**Comment by bjarnef** [comment] 2015-02-24 22:04
@warrenbuckley I think there are some issues with injecting Angular modules into Umbraco. I have tried before with property editors and think I get some errors in the console. I am not sure if it is possible to inject a custom or third party Angular module into Umbraco at the moment.

I hope this soon will be possible: http://issues.umbraco.org/issue/U4-2769

**Comment by bjarnef** [comment] 2015-02-25 08:38
@warrenbuckley can we add track by in the end of ng-repeat? that will optimize the performance - it just needs to use an unique key:
http://www.codelord.net/2014/04/15/improving-ng-repeat-performance-with-track-by/

there is a built in $id() function that can be used to assign an unique $$hashKey behind the scenes if there isn't a unique id in the properties: https://docs.angularjs.org/api/ng/directive/ngRepeat

**Comment by warrenbuckley** [comment] 2015-02-25 08:59
@bjarnef I have figured a way around injecting the AngularJS module see latest commits for clues. I am currently trying to add this to all views with tables, then I need to do a cleanup of unused sorting code in controller afterwards.

Can we move the above suggestion to a new issue, as this issue/thread is getting rather large now.

**Comment by bjarnef** [comment] 2015-02-25 10:06
@warrenbuckley I have created another issue for that suggestion.

I saw you changes about injecting a module and have seen that "trick" before, but didn't get it working at that time, when I shortly tried it. But great if it is working :)

You should can then remove the "old" sorting in the views, sort and iconSorting functions in the controllers, plus the default sorting inside the ajax request in the end.

**Comment by warrenbuckley** [comment] 2015-02-26 09:55
I have implemented the new module and removed the old code @bjarnef and will close this issue off

**Closed by warrenbuckley** 2015-02-26 09:55 UTC
Labels: bug
